{
 "title": "part_7",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Disk space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/\"}/1024/1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "100 - node_memory_MemFree_bytes / node_memory_MemTotal_bytes * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "100 - avg(rate(node_cpu_seconds_total{mode='idle'}[30s])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IO operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(node_disk_reads_completed_total) + sum(node_disk_reads_completed_total)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}